version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: config/dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./code/:/var/www/html
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - default

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./code/:/var/www/html
      - ./config/conf.d/:/etc/nginx/conf.d/
    networks:
      - default

#Docker Networks
networks:
  app-network: default
